name: Lottery System
on:
  push:
    branches:
      - master

jobs:
    lottery-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Run the lottery system
              env:
                NAME: "John_Doe"
                AGE: "25"
              run: |
                python app.py $NAME --age $AGE --lottery